language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: linux
      language: generic
      env: PIP=pip2

env:
  global:
    - TWINE_USERNAME=amaya
    - CIBW_SKIP="cp27-* cp33-*"
    - CIBW_MANYLINUX1_X86_64_IMAGE=hoshizora/manylinux1-clang-x86_64
    - CIBW_BEFORE_BUILD="yum update && yum install -y boost148 boost148-filesystem boost148-system numactl-devel && mkdir -p /tmp/manylinux1-clang && cd /tmp/manylinux1-clang && wget https://github.com/hoshizora-project/docker-manylinux1-clang/raw/master/Dockerfile-x86_64 -O Dockerfile && docker build -t hoshizora/manylinux1-clang-x86_64 . && cd -"

script:
  - pip install cibuildwheel==0.9.1
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      python3 -m twine upload wheelhouse/*.whl
    fi

