language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: linux
      language: generic
      env:
        PIP: pip3

env:
  global:
    - TWINE_USERNAME=amaya
    - CIBW_MANYLINUX1_X86_64_IMAGE=ubuntu:bionic
    - CIBW_BEFORE_BUILD="apt update && apt install -y python3 python3-pip make cmake clang-5.0 libboost-all-dev libnuma-dev"

script:
  - pip install cibuildwheel==0.9.1
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      python3 -m twine upload wheelhouse/*.whl
    fi

